In [2]:
import torch
gt = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
gt_classes = gt.long().clamp(0, 55 - 1)
gt_classes

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
class_range = torch.arange(55, device=gt.device)

class_range.view(1, -1, 1, 1, 1, 1)
class_range

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54])

In [6]:
import torch
weights = torch.ones(2,55)
weights.shape
weights
print(weights[0])
print(weights[1])

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1.])


In [8]:
def create_test_gt():
    
    H, W, D = 96, 96, 96
    gt = torch.zeros(1, 1, H, W, D)  # (B,C,H,W,D)
    
    gt[0, 0, 30:40, 30:40, 30:40] = 25 
    gt[0, 0, 50:60, 50:60, 50:60] = 30
    gt[0, 0, 70:80, 70:80, 70:80] = 54
    
    return gt

In [9]:
gt = create_test_gt()
pred = torch.randn(1, 55, *gt.shape[2:], requires_grad=True)
print(pred.shape)
print(gt.shape)

torch.Size([1, 55, 96, 96, 96])
torch.Size([1, 1, 96, 96, 96])


In [4]:
import torch
weights = torch.ones(4, 55)
weights.shape

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.

In [1]:
losses = [torch.tensor(0),torch.tensor(1),torch.tensor(2)]
a = torch.stack(losses,dim=-1)
a.shape


NameError: name 'torch' is not defined

In [17]:
import torch
H, W, D = 96, 96, 96
gt = torch.zeros(2, 1, H, W, D)  # (B,C,H,W,D)
y_pred = torch.randint(0, 55, (2, 55, H, W, D))
gt[0, 0, 30:40, 30:40, 30:40] = 25 
gt[0, 0, 50:60, 50:60, 50:60] = 30
gt[0, 0, 70:80, 70:80, 70:80] = 54
gt_classes = gt.long().clamp(0, 54)
class_range = torch.arange(55, device="cpu") # 0-54
mask = (gt_classes.unsqueeze(1) == class_range.view(1, -1, 1, 1, 1, 1)).any(dim=(2,3,4,5)).float()
print(mask)
batch_size = 2
weights = torch.ones(batch_size, 55, device=gt.device)

weights[:,0] = 1.0
weights[:,1:-1] = 1.5 * mask[:, 1:-1] + 1.0 * (1 - mask[:, 1:-1])

has_tumor = (gt == 55 - 1).any(dim=(1,2,3,4))
print(has_tumor.shape)
weights[:, -1] = torch.where(has_tumor, 
                                     3.0 * mask[:, -1], 
                                     1.0 * torch.ones_like(mask[:, -1]))

weights
print(weights.shape)


tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.]])
torch.Size([2])
torch.Size([2, 55])


In [14]:
import torch
weight = torch.zeros(55)
weight[1:-1] = 1.25
weight[-1]= 2.5
weight
5.005788803100586 - 5.005789279937744

-4.76837158203125e-07

In [7]:
(1.6936635971069336 + 1.6852390766143799 )/2.0

1.6894513368606567

In [11]:
import torch
import torch.nn as nn

input = torch.randn(1, 28,64,64,64)
x0,x1 = input.chunk(2, dim=2)
print(x0.shape)
print(x1.shape)
x0 = x0.chunk(2, dim=3)
x1 = x1.chunk(2, dim=3)
v = x0[-2]
print(v.shape)

torch.Size([1, 28, 32, 64, 64])
torch.Size([1, 28, 32, 64, 64])
torch.Size([1, 28, 32, 32, 64])


In [14]:
from monai.networks.blocks import MLPBlock

fusion_mlp = MLPBlock(64, 64)
x = torch.randn(1024,27)
o = fusion_mlp(x)
print(o.shape)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1024x27 and 64x64)

In [ ]:
fixedWeights = torch.ones(55)
fixedWeights[54] = 5.0

In [1]:
in_channels_list = ["320_conv1", "320_conv2"]
anatomy_list = [128,256]
for in_channels, anatomy in zip(in_channels_list, anatomy_list):
    print(in_channels, anatomy)

320_conv1 128
320_conv2 256


In [2]:
import numpy as np
a = [0.6352,0.6515,0.6560,0.5461,0.5994]
np.mean(a)

0.61764